export function findTopic() {
  return `You would like to start a conversation with the following topic. Please design an opening statement that includes this question and your opinion on it:
Topic: ${topics500[Math.floor(Math.random() * topics500.length)]}
Keep it short and interesting.`;
}

const topics500 = [
  "Presentation topics about science and technology",
  "AI: Mind or machine?",
  "Big Data, Big Impact: The power to change the world",
  "Biodegradable Plastics: Friend or foe?",
  "Biometrics: Should we fear the future?",
  "Climate Change: It's time to act",
  "Connected World: The impact of IoT on our lives",
  "Crypto Craze: The future of money management",
  "Cybersecurity: Protecting yourself in the digital age",
  "Digital Dimensions: Stepping into the world of VR and AR",
  "Driving the Future: The rise of autonomous vehicles",
  "Drones: Taking flight into the future",
  "Evolution: A journey through time",
  "Gene Editing and Religion: Playing with the code of life",
  "Genetics: The blueprint of life and the recipe for clones",
  "Home Sweet Smart Home: The convenience of a connected life",
  "Personal AI: How voice assistants are changing our daily lives",
  "Print Your Dreams: The future of 3D manufacturing",
  "Quantum Quirks: The fascinating world of subatomic particles",
  "Race to the Stars: Who will be the first to colonize Mars?",
  "Reality Redefined: The exciting future of virtual worlds",
  "Reality Remix: Transforming our world with augmented reality",
  "Robo Revolution: The future of automation",
  "Space Odyssey: The never-ending quest for exploration",
  "Tech Fashion: Wearable tech for the fashion-forward.",
  "The 5G Revolution: The need for speed",
  "The AI Dilemma: Ethical considerations for the future of machines",
  "The AI Takeover: A brave new world?",
  "The Brain: Unlocking the secrets of the mind",
  "The Cloud: Streamlining your digital life",
  "Tiny Tech: The marvels of nanotechnology",
  "Presentation topics about foodie culture",
  "Baking: Where science meets art",
  "BBQ: The mouthwatering tradition",
  "Bowl Wars: Acai vs. smoothie",
  "Brunch 101: The ultimate etiquette guide",
  "Brunch Voyage: Around the world in delicious meals",
  "Cast Iron: Classic cookware and more",
  "Cheese Mavericks: Artisanal and unique",
  "Chocolate Dreams: Decadent desserts",
  "Chocolate: The sweet treat of the ages",
  "Clean Eating Hypocrites: Don't be that person",
  "Coffee Culture: The roasting, brewing, and tasting journey",
  "Comfort Food Remix: Modern twists on classics",
  "Comfort Food: The warm hug we need",
  "Craft Beer Chronicles: The art of brewing and tasting",
  "Dairy-Free Delights: Non-dairy alternatives to cow's milk",
  "Eating the Rainbow: Colorful and nutritious meals",
  "Farm-to-Table: Fresh and local ingredients at your table",
  "Fermentation Nation: Ancient and modern methods",
  "Food Plating Perfection: The art of presentation",
  "Food Shamers Beware: The worst offenders",
  "Fusion Frenzy: Creative blends of culinary traditions",
  "Gluten-Free: Fad or fact?",
  "Herb and Spice Magic: Adding flavor and health to your meals",
  "Indian Spice Trail: Diverse and flavorful dishes",
  "Italian Cuisine: A journey through history and regional specialties",
  "Keto vs. Vegan: The great debate",
  "Korean BBQ: Flavor and fun at the table",
  "Life is Short, Eat Dessert First: The benefits of reversing your meal order",
  "Matcha Madness: Why we're obsessed",
  "Meal Prep Like a Pro: Healthy and delicious ideas",
  "Mediterranean Mosaic: Flavors from around the sea",
  "Mexican Street Bites: Tasty treats from vendors and markets",
  "Midnight Munchies: Why they're the best",
  "Molecular Gastronomy: Modern techniques and presentations",
  "Noodle Wars: Ramen vs. pho",
  "Organic vs. Non-Organic: What's best for your health and wallet?",
  "Plant-Based Palate: Delicious and healthy vegan meals",
  "Popcorn Playground: Endless possibilities",
  "Quarantine Baking: Crazy experiments and recipes",
  "Ramen: Delicious and comforting bowls",
  "Seafood: Sustainability and ethics on your plate",
  "Sourdough Sensation: Mastering the art",
  "Southern Comfort: Dishes from the Southern United States",
  "Street Food Safari: Adventures in food carts and trucks",
  "Sushi Symphony: Artful and delicate cuisine",
  "Thai Taste Adventure: Balanced and complex flavors",
  "The Protein Showdown: Plants vs. meat",
  "The Tea Journey: Discovering varieties, brewing methods, and traditions",
  "Umami Revolution: The best flavor ever",
  "Veganism: A plant-based lifestyle that's taking over",
  "Presentation topics about style and fashion",
  "2000s Fashion Fails: A retrospective",
  "Accessory Magic: Elevating your look with the right additions",
  "AirPods as Fashion: Style or flex?",
  "Authentic or Imitation: The fashion debate",
  "Breaking the Mold: The gender-neutral fashion movement against gender stereotypes",
  "Bucket Hats: The comeback kids",
  "Capsule Collection: Maximizing your wardrobe with minimal pieces",
  "Denim Done Right: Finding the perfect pair of jeans",
  "Fashion for Less: Chic on a shoestring budget",
  "Fashion Forward: The future of sustainability",
  "Hypebeast Hysteria: From cool to crazy",
  "K-Pop Couture: Channeling your inner idol",
  "Layering like a Boss: Style tips and tricks",
  "Pattern Play: How to mix prints like a pro",
  "Retro Revival: Thrift store treasures you need to find",
  "Street Style Influencers: When fashion meets fame",
  "Streetwear Splurges: Brands worth the investment",
  "Sweats to Streets: The athleisure revolution",
  "The Sneaker Smackdown: Jordan vs Yeezy",
  "Tie-Dye Takeover: DIY techniques for fashion fans",
  "Presentation topics about social media trends, memes, and internet culture",
  "#OOTD: The art of dressing for the internet",
  "Among Us: The game that brought us together in 2020",
  "Cancel Culture: The internet's way of holding public figures accountable",
  "Discord Delight: Where gamers and music lovers unite",
  "Drake Hotline Bling: The meme that inspired a thousand parodies",
  "Emoji-centric Language: How social media is altering our vocabulary",
  "Finsta vs. Rinsta: The difference between your fake and real Instagram accounts",
  "FOMO Frenzy: Navigating Social Media's Pressure Cooker",
  "From Hashtags to Harmful Stereotypes: How social media affects racial perceptions",
  "From Influencers To Innovators: Social media's impact on fashion trends",
  "Gen Z Gags: The wacky world of youthful humor",
  "Going Viral: Spreading joy and positivity on social media",
  "Hashtag Heroes: Using social media to make a difference",
  "Influencer, Inc.: The business of being social media cool",
  "Karen: The ultimate Karen guide to becoming a meme",
  "LinkedIn Lane: Where professionals network and thrive",
  "Lost in the Feed: How social media is impacting our ability to remember",
  "Meme Magic: The art of crafting online laughter",
  "Meme Masters: The Instagram pages that make you laugh",
  "Memes 101: A beginner's guide to internet culture",
  "Memes and Movements: How internet jokes shape political discourse",
  "Mind Your Likes: Balancing social media use and mental health",
  "Mirror, Mirror on the 'Gram: The psychological impact of social media filters",
  "NFTs: The digital art craze that no one really understands",
  "Perfectly Imperfect: The illusion of social media perfection",
  "Pizza Rat: The furry NYC hero we never knew we needed",
  "Pod Power: The audio oasis of entertainment, learning, and wellness",
  "Reddit Realms: Where niche communities thrive online",
  "Shrek-tacular: The lovable ogre that stole our hearts",
  "Snap Streaks: Keeping friendships alive one daily snap at a time",
  "Snapchat: The disappearing photo and video app that never really disappeared",
  "Social Media 2033: A glimpse into the future",
  "Social Media Bridges: Finding common ground in a divided world",
  "Social Media Politics: When posts and tweets shape society",
  "Social Media's Dark Side: Cyberbullying and online harassment",
  "Swipe Right on Marketing: The future of advertising in the digital age",
  "The Influencer Impact: How Instagram is changing the advertising game",
  "The Social Media Diet: How to break your addiction and reclaim your time",
  "The Swipe Life: The new era of social interaction",
  "TikTok Tunes: The choreography craze sweeping the internet",
  "Twitch Tribes: The online gaming communities you can't help but join",
  "Twitter Wit: The sarcastic commentary on today's events",
  "VSCO Kids: The aesthetic that's captivating social media",
  "VSCO Vibes: The subculture taking Instagram by storm",
  "We Are Number One: The song that made a villain a hero",
  "YOLO: The motto that inspired a generation",
  "YouTube Dramatics: The never-ending cycle of controversy and apologies",
  "Zillennial Woes: Caught between two generations",
  "Zoom Exhaustion: Battling burnout in the age of online meetings",
  "Zoomer Lingo: How to speak like a hip youngster",
  "Presentation topics on art and culture",
  "Art through the Ages: From cave paintings to contemporary masterpieces",
  "Artistic Expression: Creating beauty out of chaos",
  "Board Game Bonanza: From classics to new favorites",
  "Broadway Blockbusters: Singing, dancing, and show-stopping performances",
  "Cultural Cuisine: Exploring the world one dish at a time",
  "Dance Dynamo: Expressing yourself through movement",
  "Design Divas: Crafting visuals that speak volumes",
  "Fashion Forward: Designing your way to the runway",
  "Fiction Frenzy: Crafting stories that come to life",
  "Gaming Galore: Unlocking the secrets of the virtual world",
  "Global Grooves: Discovering the beats of the world",
  "Hip Hop History: From the Bronx to the top of the charts",
  "Interior Intuition: Decorating with purpose and personality",
  "Kitchen Creations: Cooking up a storm with confidence",
  "Literary Legends: Unleashing the power of words in literature",
  "Mindful Musings: Finding peace in a busy world",
  "Movie Magic: Decoding the art of cinema",
  "Music Mania: Crafting sonic sensations for Woodstock",
  "Picture Perfect: Capturing the world through the lens",
  "Poetic Prowess: Unraveling the beauty and complexity of poetry",
  "Pop Art Revolution: Bold, colorful, and groundbreaking",
  "Positive Vibes Only: Harnessing the power of optimism",
  "Street Smarts: The power of public art",
  "Sustainable Style: Fashion with a conscience",
  "The Art of Simplicity: Embracing minimalism for a better life",
  "Theater Time Warp: From ancient Greece to modern-day Broadway",
  "TV Triumphs: Why we can't get enough of the small screen",
  "Veggie Vibes: Nourishing your body and the planet",
  "Virtual Visions: Creating art in the digital realm",
  "Web Wizards: Building beautiful websites with ease",
  "Presentation topics about history",
  "Artful Mysteries: Decoding hidden meanings in famous artworks",
  "Cold War Chronicles: The ideological battle and global tensions",
  "Conquerors and Colonizers: The adventures and controversies of exploration",
  "Culture Shockers: Revolutions that shook the world and redefined society",
  "Enlightened Minds: A journey through the Age of Enlightenment",
  "Fashion Time Warp: From corsets to couture - a fashionable journey through time",
  "Gaming Through Time: The evolution of video games from Atari to Fortnite",
  "History's Wildest Tales: Separating fact from fiction in bizarre moments",
  "Industrial Evolution: How the world transformed during the Industrial Revolution",
  "Landmarks Unveiled: A visual tour of the world's most iconic sites",
  "Literary Gems: Stories that stood the test of time and transformed our world",
  "Mythic Narratives: The enduring power of storytelling and myth-making",
  "Pop Culture Odyssey: The rise and evolution of popular culture",
  "Renaissance Revolution: An explosion of creativity, science, and culture",
  "Revolutionaries Unleashed: The uprisings that changed the world",
  "Sporting Legends: The tales of heroes and legends in the world of sports",
  "Television's Golden Age: A history of the small screen and its greatest moments",
  "The Soundtrack of Our Lives: How music has shaped our society and culture",
  "Timeless Civilizations: The mysteries and wonders of ancient worlds",
  "Wars That Shaped the World: The global conflicts that changed the course of history",
  "Presentation topics about health and wellness",
  "Aging Gracefully: The secrets to healthy longevity",
  "Beyond Medicine: Unconventional ways to wellness",
  "Drink Up: The surprising benefits of hydration",
  "Finding Zen: The art of meditation",
  "Fit for Fun: The hottest exercise trends",
  "Fit in a Flash: Healthy habits for busy bees",
  "Food for Thought: Navigating the science of nutrition and your immune system",
  "Friends for Life: Nurturing social connections for wellbeing",
  "Living in the Moment: Mastering mindfulness",
  "Love the Skin You're In: Embracing body positivity",
  "Mind Matters: Nurturing your mental health",
  "Move to Improve: The benefits of functional fitness",
  "Om Your Way to Wellness: The transformative power of yoga",
  "Standing Tall: The power of posture",
  "Sweet Dreams: Unlocking the science of sleep",
  "Thanks a Million: Harnessing the power of gratitude for mental health",
  "The Mind-Body Blend: Unleashing your inner power",
  "The Perfect Fit: Ergonomics for optimal performance",
  "Unplugged: The art of digital detox for mental clarity",
  "You First: Self-care as a priority, not a luxury",
  "Presentation topics about self-development",
  "Authentic You: Crafting your personal brand for career triumph",
  "Conflict to Collaboration: Successful strategies for resolving disputes",
  "Connections that Count: Networking and relationship building for success",
  "Emo IQ: Mastering Emotions for personal and professional success",
  "From Dreams to Reality: Goal-setting strategies for achievers",
  "Harmony at Work and Play: Balancing your career and personal life",
  "Healthy Habits, Happy Life: Simple ways to improve physical and mental wellbeing",
  "Mindful Magic: Cultivating self-awareness and reducing stress",
  "Money Matters: Unlocking the secrets of financial literacy",
  "Picture Perfect: Visualization techniques for manifesting your goals",
  "Resilience Rocks: Bouncing back and thriving after adversity",
  "Rock Solid Confidence: Techniques for building unshakeable self-belief",
  "Self-Care Superstar: Daily habits for optimal health and happiness",
  "Speak Up, Stand Out: Powerful public speaking techniques for every occasion",
  "Stress Less, Live More: Coping strategies for managing life's challenges",
  "Sweat for Success: The benefits of yoga and exercise for mind and body",
  "The Write Way: Therapeutic practices for reflection and expression",
  "Think Outside the Box: Creative problem-solving for innovators",
  "Time is on Your Side: Productivity and balance techniques for busy lives",
  "Zen and the Art of Living: Incorporating Zen philosophy into your daily life",
  "Presentation topics about business",
  "Ad Magic: The art of persuasion in a modern world",
  "Brand Boom: The power of creating a recognizable image",
  "Business Battle Plan: Developing a long-term strategy for success",
  "Crowdfunding Revolution: Democratizing financing for startups and creatives",
  "Culture Creation: Building a positive and productive workplace culture",
  "Customer Delight: Creating unforgettable interactions with customers",
  "Data Decoded: Understanding business performance and customer behavior",
  "Digital Domination: Tactics for online business and product promotion",
  "E-commerce Explosion: The rise of online shopping and its impact on retail",
  "Entrepreneur Essentials: The key traits and habits for success",
  "Entrepreneur Expedition: The journey of growing a successful business",
  "Financial Future: Strategies for managing personal and business finances",
  "Innovation Ignition: New ideas to drive business growth and success",
  "Leading Legends: Essential qualities and skills of effective leaders",
  "Marketing Mastery: The art and science of promoting products and services",
  "Networking Ninja: Building professional relationships for career success",
  "Outsourcing Odyssey: The benefits and challenges",
  "Product Prodigy: From concept to launch",
  "Sales Savvy: The psychology of selling",
  "Small Business Survivors: Expecting the unexpected",
  "Social Media Superstar: How to grow on new platforms",
  "Social Savior: Business principles to address social and environmental issues",
  "Startup Spectacle: The exciting and risky world",
  "Supply Chain Saga: The complex web that brings products to market",
  "Team Titans: Leading effective teams in the workplace",
  "Presentation topics about politics and society",
  "Ballot Boxing: The fight against voter suppression",
  "Breaking Barriers: Women who paved the way in politics and feminism",
  "City Hall 101: Decoding the functions of local government",
  "Diplomacy or War: The high-stakes game of foreign relations",
  "Drawing the Line: The politics of redistricting",
  "Equality Now: The battle for civil rights",
  "Fear Factor: The political and social impacts of terrorism",
  "It's a Small World After All: The impacts of globalization on politics",
  "Locked and Loaded: The great gun debate",
  "Making a Difference: The impact of public policy",
  "Politics 101: Understanding the philosophy of governance",
  "Power Play: The art of political maneuvering",
  "Rallying the Troops: How to mobilize your community for change",
  "The Borderline: Navigating immigration policies",
  "The Great Divide: Bridging the gap in political polarization",
  "The Highest Court in the Land: Inside the inner workings of the Supreme Court",
  "The Power Behind the Throne: Inside the world of lobbying",
  "The Quest for Equality: Social justice in modern times",
  "The World is Watching: The dynamics of international relations",
  "The World Stage: Understanding the complexities of global politics",
  "Presentation topics about sustainability and the environment",
  "Carbon Offsets: The guilt-free way to lessen your carbon footprint",
  "Circular Economy: The genius of regeneration and rejuvenation",
  "Climate Change: The unavoidable reality of our planet's health",
  "Composting: Turning trash into treasure for your garden",
  "Dumpster Diving: The thrill of finding hidden gems in the trash",
  "Earth Day: The global celebration of our amazing planet and its protectors",
  "Eco-Chic: The fashionable future of sustainable clothing",
  "Eco-Friendliness: Easy and fun ways to save the planet",
  "Electric Vehicles: The fast lane to a greener future",
  "Energy Efficiency: Saving the environment and your wallet",
  "Energy Vampires: The secret life of zombie appliances",
  "Farm to City: Urban agriculture and food security",
  "Farming for the Future: Permaculture and sustainable land management",
  "Fashion with a Conscience: Sustainable style for the ethical shopper",
  "Fashion Without the Cruelty: The rise of vegan leather",
  "Fast Fashion: The not-so-pretty truth behind your cheap clothes",
  "Food Waste: The tragic tale of our wasted food and how to stop it",
  "Green Building: Constructing a sustainable and beautiful future",
  "Green Eating: The health and environmental benefits of plant-based diets",
  "Green Energy: The revolutionary tech that powers our planet",
  "Green Tech: The innovations driving us toward a sustainable tomorrow",
  "Greenwashing: Don't be fooled by the fake eco-friendly claims",
  "Influence for Good: Sustainable living with social media stars",
  "Less is More: Embracing zero waste living for a better planet",
  "Living the Vegan Life: Health, ethics, and sustainability",
  "Meatless Mondays: The weekly excuse to eat junk food and call it healthy",
  "Mindful Consumption: Harnessing the power of our purchasing choices for good",
  "Mindful Travel: Protecting the planet while exploring it",
  "Pedaling Paradise: The joyful and eco-friendly way to get around",
  "Plastic Pandemic: The impact of single-use plastics on the environment",
  "Plastic Wars: Saving our seas with ocean conservation",
  "Power from Nature: Tapping into the energy of wind, solar, and hydro power",
  "Power Up: Renewable energy and the climate change debate",
  "Public Transit Adventures: Embracing the smelly and crowded side of life",
  "Reduce, Reuse, Recycle: The basics of recycling and why it matters",
  "Reusables Rule: Making eco-friendly choices with reusable products",
  "Simplify and Declutter: The joy of minimalism",
  "Slow and Delicious: Savoring the flavors of slow food",
  "Solar Solutions: The magic of solar power without the sunburn",
  "Sustainable Cities: Pioneering the future of urban living",
  "The Recycling Dilemma: Separating fact from fiction",
  "Thrift Treasures: Secondhand shopping for sustainable style",
  "Tiny Living, Big Dreams: The excitement of downsizing with tiny houses",
  "Travel with a Purpose: Sustainable tourism for the conscious traveler",
  "Urban Jungle: Plant parenthood as a status symbol",
  "Urban Oasis: Creating a green space for apartment living",
  "Waste Not, Want Not: Upcycling for a more sustainable future",
  "Water Matters: Conserving and managing our most precious resource",
  "Wild at Heart: Preserving endangered species and their habitats",
  "Zero-Waste Warriors: Living sustainably and smugly",
  "Presentation topics about pop culture",
  "Anime-zing Adventures: Exploring the wondrous world of Japanese animation",
  "Comics Unmasked: Superheroes, villains, and everything in between",
  "Fashion Forward: Keeping up with the ever-changing trends",
  "Game of Thrones: A world of dragons, magic and intrigue",
  "Gaming Galaxies: The interactive entertainment of the 21st century",
  "Gaming Galore: A peek into the world of video games and e-sports",
  "Harry Potter and the Enchanting Wizarding World",
  "Hip-hop Hooray: The global phenomenon of music, fashion, and lifestyle",
  "K-Pop Explosion: Breaking records and boundaries",
  "Marvel-ous Universe: The epic saga of superheroes and villains",
  "Meme Magic: When humor and communication collide",
  "Netflix and Chill: How the streaming platform revolutionized entertainment",
  "Podcast Palooza: The growing popularity of on-demand audio content",
  "Reality TV Realness: Guilty pleasures, drama and competition",
  "Stranger Things: A sci-fi thriller that brings the 80s back to life",
  "The Glitz, the Glamour, the Gossip: Inside celebrity culture",
  "The Influencer Effect: How online personalities shape our lives",
  "The Office: A hilarious workplace comedy that never gets old",
  "TikTok Takes Over: A short-form video revolution",
  "True Crime Chronicles: The obsession with stories of mystery and intrigue",
  "Presentation topics about travel",
  "Cityscape Chronicles: Exploring the world's most exciting cities",
  "Dive into Culture: A journey of discovery",
  "Festival Frenzy: Where culture comes alive",
  "Food safari: Exploring the culinary landscape",
  "Foodie Frenzy: A gastronomic expedition",
  "Glamping Glamour: Where nature meets luxury",
  "Globe-Trotting Road Warriors: Epic adventures on four wheels",
  "Heritage hunt: Uncovering treasures of the past",
  "Hit the Road. Jack: The ultimate adventure on the open road",
  "Island Escapes: Hopping across paradise",
  "National Parks Unleashed: Discovering nature's wonders",
  "Nordic Nirvana: Cozy, sustainable escapes",
  "Rails and Romance: A love affair with train travel",
  "Sand, Sun, and Serenity: Beach vacations reimagined",
  "Secret Beaches: Uncovering hidden treasures",
  "Slow and Steady: Savoring the journey",
  "Solo Sojourns: Empowering adventures for one",
  "South America: Where adventure takes flight",
  "Staycation Sensations: Rediscovering your hometown",
  "The Digital Nomad Diaries: Work and wanderlust",
  "The Thrill Hunter's Handbook: Adventures that make your heart race",
  "Theme Park Thrills: Where fun never ends",
  "Thrill Me Once, Thrill Me Twice: Dare to go extreme with heart-pumping activities",
  "Trailblazing Adventures: Conquering the great outdoors",
  "Travel Lightly: A sustainable path to adventure",
  "Travel with a Conscience: Sustainable tourism at its best",
  "Vino Voyage: Sipping and savoring the best of wine country",
  "Wildlife Wonders: Awe-inspiring encounters with nature",
  "Winter Warriors: Embracing the chill with winter sports",
  "Winter Wonderland: A magical escape to snowy paradises",
  "Presentation topics about sports",
  "Adaptive sports: Overcoming physical obstacles to achieve greatness",
  "American football: The gridiron gladiators and the strategy of smashing success",
  "Archery: Bullseyes, bows, and the beauty of precision",
  "Baseball: America's pastime: the crack of the bat and the roar of the crowd",
  "Basketball: Dribbling, dunking, and dominating the court",
  "Boxing: Ropes, punches, and the sweet science of knockouts",
  "Cricket: Wickets, runs, and the genteel game of cricket",
  "Crossfit: Sweating, sculpting, and the science of functional fitness",
  "Cycling: The wheels that take you on a journey to health and freedom",
  "Dance: Art, rhythm, and the expression of the soul through movement",
  "Esports: From virtual to reality: the high-stakes world of video games",
  "Extreme sports: Adrenaline-fueled adventure and defying limits",
  "Fantasy sports: The online realm where stats and strategy reign supreme",
  "Golf: The greens, the clubs, and the thrill of the swing",
  "Gymnastics: Balancing, flipping, and the magic of the mats",
  "Mixed martial arts: Fists, feet, and the fighting styles of MMA",
  "Olympic history: The triumphs, the scandals, and the global celebration of sportsmanship",
  "Parkour: Urban ninja skills and the art of movement through the city",
  "Rugby: Tackles, scrums, and the hooligan's game played by gentlemen",
  "Running: The beat of your heart and the rhythm of your feet",
  "Skateboarding: Tricks, flips, and the evolution of a subculture",
  "Skiing: From snowplows to black diamonds, the thrill of the slopes",
  "Soccer: Goals, passes, and the beautiful game that unites the world",
  "Surfing: Riding waves, chasing swells, and the culture of the surf",
  "Swimming: Strokes, breaths, and the meditative benefits of the water",
  "Tennis: The elegance, the power, and the passion of the racket sport",
  "Track and field: Sprinting, jumping, and the glory of the gold medal",
  "Ultimate frisbee: Frisbees, teamwork, and the ultimate game of flying discs",
  "Volleyball: Bumps, sets, and the spike of victory",
  "Women's sports: The rise, the power, and the unstoppable force of female athleticism",
  "Presentation topics about conspiracy theories",
  "Aliens: The truth is out there, but we're not being told",
  "Ancient astronauts: Did extraterrestrials influence past human civilizations?",
  "Area 51: The aliens among us",
  "Bermuda Triangle: The mysterious disappearances",
  "Chemtrails: The conspiracy in the sky",
  "Flat Earth: The truth is out there",
  "Hollow Earth: The bizarre theory that there's a whole world beneath our feet",
  "Illuminati: The secret society that rules the world",
  "Mandela Effect: Remembering a different reality",
  "Moon landing: Was it real or a hoax?",
  "New World Order: The sinister plan for global domination",
  "Parallel Universes: Are there alternate versions of reality beyond our own?",
  "Reptilian Elite: Are our leaders actually lizard people?",
  "Roswell: The UFO crash that started it all.",
  "Simulation Theory: Are we living in a computer program?",
  "The Philadelphia Experiment: Time travel and teleportation",
  "The Titanic: Was it really the Titanic that sank?",
  "The Voynich Manuscript: The unbreakable code",
  "Time Travel: Is it possible and are we already doing it?",
  "Zombie Apocalypse: Are we prepared for the end of the world?",
  "Presentation topics about weird history",
  "Abe Lincoln's Wrestling Career: The lesser-known talents of the 16th US President",
  "Æthelred the Unready: The king of England who was unready for anything",
  "Cotard Delusion: The rare mental disorder that makes people believe they are dead",
  "Dancing Mania: The bizarre phenomenon of spontaneous dance parties in the Middle Ages",
  "Dark Web: The hidden corner of the internet where anything is for sale",
  "Krampus: The demonic companion of Saint Nicholas",
  "Mary Celeste: The ghost ship that was found adrift with no crew",
  "Mummy unwrapping parties: The creepy and curious craze of the Victorian era",
  "Phrenology: The misguided practice of reading personality traits based on head shape",
  "Rat Kings: The bizarre phenomenon of rats getting their tails tangled together",
  "Tulip Mania: The wild and crazy world of 17th-century Dutch tulip speculation",
  "Victorian Slang: The weird and wonderful language of the 19th century",
  "Viking Sagas: The epic and often strange tales of Norse mythology and history",
  "Witch Hunts: The dark and disturbing history of hunting and persecuting supposed witches",
  "Zombie Apocalypse: The real-life inspirations behind our favorite undead stories",
  "Presentation topics about superpowers",
  "Flight: The power to soar through the skies like a bird",
  "Invisibility: The ability to disappear from sight at will",
  "Mind reading: The power to know what others are thinking",
  "Pyrokinesis: The power to control and create fire",
  "Regeneration: The ability to heal from any injury or illness",
  "Shapeshifting: The power to transform into any shape or form",
  "Super strength: The ability to lift and move objects beyond human capacity",
  "Telekinesis: The power to move objects with the mind",
  "Teleportation: The power to instantly transport oneself anywhere",
  "X-ray vision: The power to see through objects and clothing",
  "Presentation topics about mythical creatures",
  "Bigfoot: The elusive legend of the forest",
  "Centaurs: The majestic hybrid of mythology",
  "Chupacabra: Myth or menace? The legend of the bloodsucking beast",
  "Cyclops: The one-eyed wonder of ancient Greece",
  "Dragons: Mythical creatures that ignite our imagination and fears",
  "Elves: Beyond Santa's helpers: a look into mythology's most mysterious creatures",
  "Fairies: Fantasy or reality? The enchanting world of the Fae",
  "Gargoyles: Winged guardians of Gothic architecture and mythology",
  "Griffins: The mighty beasts that ruled ancient mythology",
  "Kraken: The deep-sea giant that haunts our imagination",
  "Loch Ness Monster: The enduring mystery of Nessie and the Scottish Highlands",
  "Mermaids: The enigmatic creatures of the sea that have captivated us for centuries",
  "Minotaur: The terrifying creature that was half-man, half-bull",
  "Phoenix: The majestic bird of fire and rebirth that rises from the ashes",
  "Sasquatch: The mythical beast that roams the forests of the Pacific Northwest",
  "Sirens: The alluring and dangerous temptresses of Greek mythology",
  "Sphinx: The legendary creature that stands guard over the mysteries of the Pyramids",
  "Unicorns: The graceful and magical beasts of fairy tales and legend",
  "Yeti: The mysterious abominable snowman of the Himalayas",
  "Zombies: The walking dead that won't stay dead",
  "Presentation topics about gaming",
  "Console or PC? Let's end the debate once and for all",
  "Gaming in Comfort: Ergonomic chair setup",
  "Immerse Yourself: The best virtual reality gaming experiences",
  "Loot Boxes: Is your addiction ruining your life?",
  "Mind Games: The psychology of e-sports",
  "Need for Speed: Tips for successful speedrunning",
  "Streaming like a Pro: Setting up your Twitch channel",
  "Talking to NPCs: Analyzing the dialogue of video games",
  "The Art of Rage Quitting: The dos and don'ts",
  "The Art of Stealth: Tips and tricks for sneaking around",
];
